language: node_js
node_js:
  - "8"
codecov --token=: 4ba9c6a7-b0fe-4540-a784-411a79e77d83
after_success:
- ./bin/codecov -e TRAVIS_NODE_VERSION
install:
  - npm install -g codecov
  - npm install -g istanbul
  - npm install -g mocha
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
